version: '2'

services:
  app:
    build:
      context: ./
      dockerfile: Dockerfile
    ports:
      - "8080:8080"
    environment:
      - "MYSQL_DATABASE=imdb"
      - "MYSQL_USER=imdb_app"
      - "MYSQL_PASSWORD=secret_imdb_app"
      - "MYSQL_ROOT_PASSWORD=super_secret_imdb_app"
    networks:
      - imdbapi

  mysqlDB:
    image: "mysql:5.7"
    ports:
      - "3306:3306"
    environment:
      - "MYSQL_DATABASE=imdb"
      - "MYSQL_USER=imdb_app"
      - "MYSQL_PASSWORD=secret_imdb_app"
      - "MYSQL_ROOT_PASSWORD=super_secret_imdb_app"
    networks:
      - imdbapi

networks:
  imdbapi:
    driver: "bridge"
