version: '2'

services:
  app:
    build:
      context: ./
      dockerfile: Dockerfile
    ports:
      - "8080:8080"
    environment:
      - "MONGO_HOSTS=mongoDB:27017"
      - "MONGO_USER=user"
      - "MONGO_PASS=pass"
      - "MONGO_DATABASE=simple_imdb_api"
    networks:
      - imdbapi

  mongoDB:
    image: "mongo:3.0"
    ports:
      - "27017:27017"
    environment:
      - "MONGO_INITDB_ROOT_USERNAME=user"
      - "MONGO_INITDB_ROOT_PASSWORD=pass"
      - "MONGO_INITDB_DATABASE=simple_imdb_api"
    networks:
      - imdbapi

networks:
  imdbapi:
    driver: "bridge"
